export enum AuthMessages {
  SignupUserSuccess = "You have successfully signed up",
  SigninUserSuccess = "You have successfully signed in",
  AlreadyRegistered = "Already signup with username or email",
  NotFoundUser = "User not found",
  InvalidPassword = "Invalid identifier or password",
  InvalidAccessToken = "Invalid access token",
  NotFoundRefreshToken = "Refresh token not found",
  RefreshTokenSuccess = "Refreshed token successfully",
  SignoutSuccess = "You have successfully signed out",
  AlreadyVerifyEmail = "This email already verified",
  SendedResetPassword = "The password reset link has been sent to your email",
  AlreadySendMail = "An email has already been sent to you. Please try again in 10 minutes",
  ResetPasswordSuccess = "Password rested successfully",
  NotFoundToken = "Token not found",
  SendVerifyEmailSuccess = "Send verify email successfully",
  verifiedEmailSuccess = "verified email successfully",
  VerifyYourEmail = "Verify your email before accessing this site",
}
